### ISSUE TITLE
install-debuntu.sh fails to grep ip address

### ISSUE THREAD

**Issue by ehaskell1** [jellyfin/jellyfin-repo-helper-scripts#3]
This refers to https://repo.jellyfin.org/install-debuntu.sh

On my machine, line 267 prints `http://:8096`. The grep on line 260 fails to find any matching lines because the line it needs to match is `    inet 192.168.0.22/24 brd 192.168.0.255 scope global noprefixroute enp0s31f6`.

Relevent excerpt of the script:

```
IP_ADDRESS="$( ip address show dev "${GATEWAY_IFACE}" \
               | grep -w "inet .* scope global ${GATEWAY_IFACE}$" \     <--- line 260
               | awk '{ print $2 }' \
               | awk -F '/' '{ print $1 }' )"

echo "You can access your new instance now at http://${IP_ADDRESS}:8096 in your web browser to finish setting up Jellyfin."
^^^ line 267 ^^^
```

**Comment by joshuaboniface** [comment]
Should be a pretty easy fix, we can just remove `scope global` to get it to match. If you do that and run that command does it show the correct IP?

**Comment by ehaskell1** [comment]
> If you do that and run that command does it show the correct IP?

Yes.

**Comment by joshuaboniface** [comment]
Fix pushed, thanks for reporting!
